# action.yml
name: 'Gateway Conformance Tests: Extract Fixtures'
description: 'Extracts the fixtures from the Gateway Conformance Tests'
inputs:
  output:
    description: 'The path where the fixtures will be saved'
    required: true
    default: 'fixtures'
runs:
  using: 'composite'
  steps:
    - name: Prepare for the extraction
      id: prepare
      env:
        OUTPUT: ${{ inputs.output }}
      run: |
        mkdir -p "$OUTPUT"
        echo "repository=$GITHUB_ACTION_REPOSITORY" >> $GITHUB_OUTPUT
        echo "ref=$GITHUB_ACTION_REF" >> $GITHUB_OUTPUT
      shell: bash
    - name: Extract the fixtures
      uses: pl-strflt/docker-container-action@v1
      env:
        OUTPUT: ${{ inputs.output }}
      with:
        repository: ${{ steps.prepare.outputs.repository || github.repository }}
        ref: ${{ steps.prepare.outputs.ref || github.sha }}
        dockerfile: Dockerfile
        args: extract-fixtures "$OUTPUT"
