# action.yml
name: 'Gateway Conformance Tests: Extract Fixtures'
description: 'Extracts the fixtures from the Gateway Conformance Tests'
inputs:
  output:
    description: 'The path where the fixtures will be saved'
    required: true
    default: 'fixtures'
runs:
  using: 'composite'
  steps:
    - id: action
      run: |
        if [[ $GITHUB_ACTION_PATH == */_actions/* ]]; then
          echo "repository=$(echo ${GITHUB_ACTION_PATH#*/_actions/} | cut -d/ -f1-2)" >> $GITHUB_OUTPUT
          echo "ref=$(echo ${GITHUB_ACTION_PATH#*/_actions/} | cut -d/ -f3)" >> $GITHUB_OUTPUT
        else
          echo "repository=$GITHUB_REPOSITORY" >> $GITHUB_OUTPUT
          echo "ref=$GITHUB_SHA" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Extract the fixtures
      uses: pl-strflt/docker-container-action@v1
      env:
        OUTPUT: ${{ inputs.output }}
      with:
        repository: ${{ steps.action.outputs.repository }}
        ref: ${{ steps.action.outputs.ref }}
        dockerfile: Dockerfile
        args: extract-fixtures "$OUTPUT"
