# action.yml
name: 'Gateway Conformance Tests: Extract Fixtures'
description: 'Extracts the fixtures from the Gateway Conformance Tests'
inputs:
  output:
    description: 'The path where the fixtures will be saved'
    required: true
    default: 'fixtures'
runs:
  using: 'composite'
  steps:
    - env:
        OUTPUT: ${{ inputs.output }}
      run: docker run --workdir /github/workspace --rm -e CI=true -v "$PWD":"/github/workspace" ghcr.io/ipfs/gateway-conformance:latest "extract-fixtures" "$OUTPUT"
      shell: bash
